version: "3.7"

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=homestead
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret

  app:
    image: ambientum/php:7.3-nginx
    container_name: laravel-passport-notification
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - redis
      - mailhog
  redis:
    image: redis
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

  worker:
    image: ambientum/php:7.3
    command: 'php artisan queue:work'
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - redis
      - mailhog
